name: Build on Push

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: macOS-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'  # Specify the Xcode version you need

      - name: Install Dependencies
        run: |
          # Add commands to install any dependencies here
          # For example, if you're using CocoaPods:
          # pod install

      - name: Build Project
        run: |
          xcodebuild -scheme xcode/joke -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Archive Project
        run: |
          xcodebuild -scheme xcode/joke -sdk iphoneos -configuration Release archive -archivePath ./build/joke.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

